# https://www.addictedtotech.net/nginx-proxy-manager-tutorial-raspberry-pi-4/

# [[Copy and paste lines below beginning with 'version'   ]]
#
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "pi"
      DB_MYSQL_PASSWORD: "BeaVisunDButth3ad"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'zT20RabcX9'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'pi'
      MYSQL_PASSWORD: 'BeaVisunDButth3ad'
    volumes:
      - ./data/mysql:/var/lib/mysql
#
#
#[[now run with]]]
#
# sudo docker-compose up -d
